### ISSUE TITLE
【微步在线】

### ISSUE THREAD

**Issue by hujunfei** [CoderLeixiaoshuai/wuhan-IT#12]
## 微步在线

<p align="center">
<img src="https://www.threatbook.cn/assets/logo-red.svg" height="100">
</p>

**1、简介**

> 微步在线致力于成为企业客户的威胁发现和响应专家。公司从成立初始便专注于威胁情报领域，积累了深厚的威胁分析能力和威胁情报数据能力，并以专业的产品赋能给客户，帮助客户落地威胁情报能力、建立全方位的威胁监控体系。
公司连续三次入选 Gartner 《全球威胁情报市场指南》，多次入选全球网络安全 500 强，并获“红鲱鱼亚洲 100 强”称号。
>
> 目前已融资到 E 轮

**2、薪资福利**

九险一金、租房补贴、法定节假日+司龄假、学习补贴报销、包晚餐等

**3、工作时间**

10：00 - 20：00，周末双休

**4、工作地点**

武汉市洪山区光谷时代广场A座

**Comment by CoderLeixiaoshuai** [comment]
已合入，感谢贡献！
